version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "saturday"
      time: "17:00"
      timezone: "Asia/Tokyo"
    cooldown:
      default-days: 7
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "17:00"
      timezone: "Asia/Tokyo"
    cooldown:
      default-days: 7
